#!/bin/bash
ver="1.095"
dispage=0
if [[ "$1" == "" ]]; then
  echo "     cuss by BladeMight, v$ver"
  echo "$0 <search-query> <page-number> <sort-type>"
  echo "Page number can be range: 1-3."
  echo "Sort types:"
  echo "  0 - Relevance"
  echo "  1 - Date"
  echo "  2 - Views"
  echo "  3 - Comments"
  echo "  4 - Rating"
  exit
fi
debug=0
date=0
if [[ "$1" == "--date" ]]; then
  date=1
  shift
fi
if [[ "$1" == "-d" ]]; then
  debug=1
  shift
fi
u="$1"
#u=$(node -e "console.log(encodeURIComponent(process.argv[1]))" "$1")
u=$(echo "$u" | iconv -f utf-8 -t cp1251)
u=$(echo "$u" | php -R 'echo urlencode($argn);')
#u=$(echo "$u" | sed -re 's/%20/+/g')
#u=$(echo "$1" | iconv -f utf-8 -t cp1251) #| php -R 'echo urlencode($argn);')
# php -R 'echo urlencode($argn);')
p=1
s=1
if [[ "$2" != "" ]]; then
  p=$2
fi
if [[ "$3" != "" ]]; then
  s=$3
fi
#echo "$p + $u"
U="https://video.sibnet.ru/search.php?panel=open&text=$u&sortby=$s&inname=1&rubid=0&userlogin=&duration=0&page="
shantak() {
  H1="Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8"
  #H2="Accept-Encoding: utf-8, cp1251"
  H2="Accept-Encoding: gzip, deflate, br"
  H3="Accept-Language: ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7,zh-CN;q=0.6,zh;q=0.5"
  H4="Connection: keep-alive"
  H5="Host: video.sibnet.ru"
  if [[ $dispage -eq 1 ]]; then
    echo "Page: $1 [$U$1]"
  fi
  r=$(curl -H"$H1" -H"$H2" -H"$H3" -H"$H4" -H"$H5" -s "$U$1" --compressed | iconv -f cp1251 -t utf-8)
  if [[ $debug -eq 1 ]]; then
    echo "Responce of \"$U$1\" saved to: res.html"
    echo -e "$r" > res.html
  fi
  if [[ "$r" == "" ]]; then
    echo "Error occured: Empty responce."
    exit 24
  fi
  sear=$(echo "$r" | grep -Po '<a href="(\/video[0-9]+).+?">.+?(title)="(.+?)"' | perl -pe 's/^<a href="(\/video[0-9]+).+?">.+?(title)="(.+?)"$/\3\nhttps:\/\/video.sibnet.ru\1\//g' | sed 's/&nbsp;/ /g; s/&amp;/\&/g; s/&lt;/\</g; s/&gt;/\>/g; s/&quot;/\"/g; s/#&#39;/\'"'"'/g; s/&ldquo;/\"/g; s/&rdquo;/\"/g;' | sed -re 's/<\/?b>//g')
  if [[ $date -eq 1 ]]; then
    datr=()
    while IFS='' read -r datl || [[ -n "$datl" ]]; do
      datl=$(echo "$datl" | perl -pe 's/\r//g')
      datr=("${datr[@]}" "$datl")
    done < <(echo "$r" | perl -ne 'while(/>([0-9]{2}\.[0-9]{2}\.[0-9]{2,4}.+?)</g){ my $a = $1; $a =~ s/\&nbsp;/ /; print "$a\n"; }')
    c=0
    co=0
    while IFS='' read -r seal || [[ -n "$seal" ]]; do
      if [[ $c -eq 2 ]]; then
        echo "${datr[$co]}"
        echo "----"
        c=0
        co=$((co+1))
      fi
      echo "$seal"
      c=$((c+1))
    done < <(echo "$sear")
    echo "${datr[$co]}"
    echo "----"
  else
    echo "$sear"
  fi
}
if [[ $2 =~ ^[0-9]-[0-9]$ ]]; then
  dispage=1
  st="${2%%-*}"
  en="${2##*-}"
  echo "Range mode: $st => $en"
  for i in $(seq $st $en); do 
    shantak $i
  done
else
  shantak $p
fi

